---
- name: Core - Update apt Packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: full
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Core - Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Core - Reboot if required
  ansible.builtin.reboot:
    msg: Rebooting due to a kernel update
  when: (ansible_distribution in ["Ubuntu", "Debian"]) and reboot_required_file.stat.exists

- name: Core - Install Required Packages
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present

- name: Core - Create container_dir and set permissions
  ansible.builtin.file:
    path: "{{ container_dir }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: Core - Create data_dir and set permissions
  ansible.builtin.file:
    path: "{{ container_dir }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: Core - Create media_dir and set permissions
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
  loop:
    - "{{ media_dir }}"
    - "{{ media_dir }}/movies"
    - "{{ media_dir }}/tv"
    - "{{ media_dir }}/music"
    - "{{ media_dir }}/anime"
    - "{{ media_dir }}/downloads"

- name: Core - Create Service Directories and set permissions
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
  loop:
    - "{{ container_dir }}/traefik"

- name: Core - Disable login messages
  ansible.builtin.file:
    name: /home/{{ username }}/.hushlogin
    mode: "0644"
    state: touch
    owner: "{{ username }}"
    group: "{{ username }}"
    modification_time: preserve
    access_time: preserve
